const TICK_RATE = 30;
const TICK_INTERVAL_MS = 1000 / TICK_RATE;
const SNAPSHOT_HISTORY_SIZE = 64;
const MAX_ENTITIES = 1024;

module.exports = {
  TICK_RATE,
  TICK_INTERVAL_MS,
  SNAPSHOT_HISTORY_SIZE,
  MAX_ENTITIES,
};
